repos:
  - repo: https://github.com/ambv/black
    rev: stable
    hooks:
      - id: black
        args: [--line-length=88, --safe]
        python_version: python3.6
  - repo: https://github.com/asottile/seed-isort-config
    rev: v1.0.0
    hooks:
      -  id: seed-isort-config
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v4.3.4
    hooks:
      - id: isort
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v1.2.3
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: debug-statements
  - repo: local
    hooks:
      - id: py36
        name: py36
        language: system
        entry: pipenv run tox -r -e py36
        types: [python]
      - id: py37
        name: py37
        language: system
        entry: pipenv run tox -r -e py37
        types: [python]
      - id: flake8
        name: flake8
        language: system
        entry: pipenv run tox -r -e flake8
        types: [python]
      - id: pylint
        name: pylint
        language: system
        entry: pipenv run tox -r -e pylint
        types: [python]
      - id: mypy
        name: mypy
        language: system
        entry: pipenv run tox -r -e mypy
        types: [python]
  - repo: https://github.com/Lucas-C/pre-commit-hooks-go
    rev: v1.0.0
    hooks:
      - id: checkmake
  - repo: https://github.com/jorisroovers/gitlint
    rev: v0.10.0
    hooks:
      - id: gitlint
        stages: [commit-msg]
  - repo: https://github.com/Yelp/detect-secrets
    rev: 0.10.1
    hooks:
      - id: detect-secrets
        exclude: Pipfile*
