repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v1.2.3
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: debug-statements
  - repo: https://github.com/jorisroovers/gitlint
    rev: v0.10.0
    hooks:
      - id: gitlint
        stages: [commit-msg]
  - repo: https://github.com/Yelp/detect-secrets
    rev: 0.10.1
    hooks:
      - id: detect-secrets
        exclude: Pipfile*
  - repo: https://github.com/Lucas-C/pre-commit-hooks-go
    rev: v1.0.0
    hooks:
      - id: checkmake
