repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v1.4.0-1
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
  - repo: https://github.com/jorisroovers/gitlint
    rev: v0.10.0
    hooks:
      - id: gitlint
        stages: [commit-msg]
  - repo: https://github.com/Yelp/detect-secrets
    rev: 0.10.3
    hooks:
      - id: detect-secrets
        exclude: Pipfile*
        exclude: .pre-commit-config.yaml
        exclude: .travis.yml
